spring.application.name=dr
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=doctor_dr;encrypt=true;trustServerCertificate=true
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=doctor_user
spring.datasource.password=SuserP@ssw0rDdoctor123
# Optional: JPA config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
#logging.level.org.springframework=debug
spring.config.import= optional:secrets.properties

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${internal-system.internal-email}
spring.mail.password=${internal-system.internal-email-password}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

